name: controle_financeiro_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5

  # Gerenciamento de Estado
  flutter_riverpod: ^2.5.1

  # UI & Gráficos
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0

  # Login Social
  google_sign_in: ^6.2.1

  # Utilitários
  rxdart: ^0.27.7
  intl: ^0.19.0 # Para formatação de datas e moedas

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true